### ISSUE TITLE
Search field not showing up at 6.x

### ISSUE THREAD

**Issue by maziminke** [tpartner/LimeSurvey-Searchable-Dropdown-6x#1]
I have installed this theme and then used the new theme for a single question. But at question preview the search field is not showing up at all.
Tested with v 6.5.2.

**Comment by tpartner** [comment]
I have just successfully installed it in version 6.5.3. The questions work as expected.

Ensure that you have followed the readme instructions exactly - you cannot install directly from the _LimeSurvey-Searchable-Dropdown-6x-main.zip_ file downloaded from here, you need to extract the download, compress (zip) the _Searchable-Dropdown_ folder and import from **_Searchable-Dropdown.zip_**.

**Comment by maziminke** [comment]
RTFM classic, my bad :-)
